org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

minecraft_version=26.1
loader_version=0.19.1
fabric_api_version=0.145.4+26.1
loom_version=1.17-SNAPSHOT
org.gradle.configuration-cache=false

mod_version=6.5.32
maven_group=dev.jab125
archives_base_name=minimega

fantasy_version=0.8.0+26.1.2
map_templates_version=0.3.0+26.1
legacy4j_compat_version=6.5.32-1.9
